ops:
  load_data:
    config:
      file_path: '/Users/level3/TrackAI/BikeEnv/bikes_rent/src/spotify_data.csv'
      raw_data_path: "/Users/level3/TrackAI/BikeEnv/bikes_rent/src/spotify_data.csv"
      drop_columns: ["track_id", "unnecessary_column"]

assets:
  load_data:
    config:
      file_path: "/Users/level3/TrackAI/BikeEnv/bikes_rent/src/spotify_data.csv"

resources:
  mlflow:
    config:
      tracking_uri: "http://localhost:5010"
      experiment_name: "Dagster_Mlflow"
